# Generated by Django 5.1.3 on 2025-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employ_no", models.CharField(max_length=6)),
                ("score", models.IntegerField(max_length=3)),
            ],
        ),
    ]
