# Generated by Django 5.1.3 on 2025-04-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pg035_sqlite_connect", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="id",
        ),
        migrations.AlterField(
            model_name="score",
            name="employ_no",
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.IntegerField(),
        ),
    ]
