# Generated by Django 5.1.3 on 2025-04-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pg035_sqlite_connect", "0002_remove_score_id_alter_score_employ_no_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="score",
            table="score",
        ),
    ]
