# Generated by Django 5.1.3 on 2025-04-07 10:40

import pg035_sqlite_connect.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pg035_sqlite_connect", "0003_alter_score_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="employ_no",
            field=pg035_sqlite_connect.models.FixedCharField(
                max_length=6, primary_key=True, serialize=False
            ),
        ),
    ]
